{% set name = "nionswift" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #Use pypi for the next release, source distribution missing files
  #url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  #sha256: 1f0aae216af499bf0c4e6e2571bd37d53ee75096866fa4266c9014d6d31fffb5
  url: https://github.com/nion-software/nionswift/archive/{{ version }}.tar.gz
  sha256: cd8a302982b4b7cc20ee8f09e3eddccf6e588d92a97b578ac3a6ed4d33067e3c

build:
  number: 0
  noarch: python
  entry_points:
    - nionswift=nion.swift.command:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py
    - imageio
    - niondata >=0.13.6
    - nionswift-io
    - nionui >=0.3.25
    - nionutils >=0.3.17,<0.4.0
    - numpy
    - pillow
    - python >=3.6
    - pytz
    - scipy
    - tzlocal

test:
  imports:
    - nion.swift
    - nion.swift.model
    - nion.swift.test
    - nion.typeshed
    - nionlib
    - nionswift_plugin.none
    - nionui_app.nionswift

about:
  home: http://nion.com/swift
  license: GPL3
  license_file: LICENSE
  summary: 'Nion Swift: Scientific Image Processing'
  doc_url: https://nionswift.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/nion-software/nionswift

extra:
  recipe-maintainers:
    - cmeyer
    - ericpre
